// Isolate one verified snapshot's registered boss rig before clip packaging.
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {prune} from '@gltf-transform/functions';
import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
const type=process.argv[2],tag=process.argv[3]??'final-v1',dir=process.env.MESHY_RIG_OUTPUT;
if(!dir||!['chalawan','bamboo_grave_3','sealed_mine_3'].includes(type))throw Error('Explicit output directory/type required');
const report=JSON.parse(await fs.readFile(`${dir}/${type}-rig-report.json`)),journal=JSON.parse(await fs.readFile(`${dir}/${type}-${tag}-export.json`));
const receipt=journal.jobs.find(j=>j.format==='glb')?.verifiedStatus?.artifact;
if(!receipt)throw Error('Export must complete and verify first');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
if(hash(await fs.readFile(receipt.path))!==receipt.sha256)throw Error('Export hash mismatch');
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS),doc=await io.read(receipt.path),root=doc.getRoot();
const rig=root.listNodes().find(n=>n.getName()===report.rigName),surface=root.listNodes().find(n=>n.getName()===report.surfaceName);
if(surface?.getParentNode()!==rig||surface.getSkin()?.getName()!==report.rigName)throw Error('Wrong authored mesh/skin hierarchy');
const keep=new Set();function visit(n){keep.add(n);n.listChildren().forEach(visit);}visit(rig);
const scene=root.listScenes()[0];for(const s of root.listScenes())for(const n of s.listChildren())s.removeChild(n);scene.addChild(rig);
for(const a of root.listAnimations())if(a.getName()!==report.rigName+'Action')a.dispose();
for(const n of root.listNodes())if(!keep.has(n))n.dispose();await doc.transform(prune());
if(root.listMeshes().length!==1||root.listSkins().length!==1||root.listAnimations().length!==1)throw Error('Expected one authored animated surface');
const output=`${dir}/${type}-rig-production.glb`;await io.write(output,doc);
await fs.writeFile(`${dir}/${type}-production-extract.json`,JSON.stringify({type,sourceSha256:receipt.sha256,outputSha256:hash(await fs.readFile(output))},null,2)+'\n');
console.log(type,output);
