const fs=require('node:fs');const{chromium}=require('C:/Users/panup/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{fs.mkdirSync('artifacts/gm-review',{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true}),out=[];try{for(const[name,width,height]of[['desktop',1440,900],['portrait',390,844],['landscape',844,390]])for(const admin of[false,true]){const p=await b.newPage({viewport:{width,height},hasTouch:name!=='desktop'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5205/tools/gm-review.html'+(admin?'?admin=1':''));await p.waitForFunction(()=>window.gmReview);if(admin)await p.locator('.chat-gm-toggle').click();const checks=await p.evaluate(({width,height})=>{const r=gmReview.chat.root.getBoundingClientRect();return{buttons:document.querySelectorAll('.chat-gm-toggle').length,commands:document.querySelectorAll('.chat-gm-help button').length,withinViewport:r.x>=0&&r.y>=0&&r.right<=width&&r.bottom<=height,overflows:document.documentElement.scrollWidth>width};},{width,height});await p.screenshot({path:`artifacts/gm-review/${name}-${admin?'admin':'regular'}.png`});if(admin){await p.locator('.chat-gm-toggle').click();checks.historyRestored=await p.locator('.net-lines').isVisible();await p.locator('.chat-gm-toggle').click();await p.locator('.chat-gm-help button').filter({hasText:'/gm admin'}).click();checks.clickSeedsOnly=await p.locator('.chat-message').inputValue()==='/gm admin ';checks.clearRevocation=await p.evaluate(()=>{gmReview.chat.add('GM','private help','gm');gmReview.chat.setGmCatalog(null);return!document.querySelector('.chat-gm-toggle,.chat-gm-help,.net-lines .gm');});}
checks.channels=await p.evaluate(()=>{const c=gmReview.chat,sent=[];c.filter=t=>{sent.push(t);return true};c.open();c.select('party');c.input.value='hello';c.submit();c.open();c.select('whisper');c.recipient.value='Friend';c.input.value='secret';c.submit();c.open();c.select('general');c.input.value='world';c.submit();return JSON.stringify(sent)===JSON.stringify(['/p hello','/w Friend secret','world']);});
await p.evaluate(()=>{gmReview.chat.open();gmReview.chat.input.value='abcd';gmReview.chat.input.setSelectionRange(1,3);});await p.locator('.chat-emoji-toggle').click();await p.locator('.chat-emoji-picker button').filter({hasText:'🙏'}).click();checks.emoji=await p.locator('.chat-message').inputValue()==='a🙏d';await p.evaluate(()=>gmReview.chat.input.value='x'.repeat(120));await p.locator('.chat-emoji-toggle').click();await p.locator('.chat-emoji-picker button').first().click();checks.emojiLimit=(await p.locator('.chat-message').inputValue()).length===120;
await p.locator('#chat-tab-general').focus();await p.keyboard.press('ArrowRight');checks.keyboardTab=await p.evaluate(()=>gmReview.chat.channel==='party');await p.locator('.chat-message').focus();await p.keyboard.press('Escape');checks.collapse=await p.evaluate(()=>gmReview.chat.input.hidden&&gmReview.chat.emojiPicker.hidden&&gmReview.chat.collapsed===(innerWidth<=900||document.body.classList.contains('ui-touch')));
checks.offline=await p.evaluate(()=>{const c=gmReview.chat;c.open();c.select('general');c.setStatus(false);c.input.value='keep';c.submit();return c.input.value==='keep'&&!c.feedback.hidden;});
if(await p.locator('.drag-lock').isVisible()){await p.locator('.drag-lock').click();const initial=await p.evaluate(()=>gmReview.chat.root.style.translate),bar=await p.locator('.net-online').boundingBox();await p.mouse.move(bar.x+bar.width/2,bar.y+bar.height/2);await p.mouse.down({button:'right'});await p.mouse.move(bar.x+bar.width/2+30,bar.y+bar.height/2+10);await p.mouse.up({button:'right'});checks.rightDrag=await p.evaluate(initial=>gmReview.chat.root.style.translate===initial,initial);await p.keyboard.press('Escape');const freshBar=await p.locator('.net-online').boundingBox();await p.mouse.move(freshBar.x+freshBar.width/2,freshBar.y+freshBar.height/2);await p.mouse.down();await p.mouse.move(freshBar.x+freshBar.width/2+30,freshBar.y+freshBar.height/2+10,{steps:5});await p.mouse.up();checks.leftDrag=await p.evaluate(initial=>gmReview.chat.root.style.translate!==initial,initial);
}else{checks.rightDrag=null;checks.leftDrag=null;checks.touchDragLocked=true;}out.push({name,admin,...checks,errors});await p.close();}}finally{await b.close();}fs.writeFileSync('artifacts/gm-review/checks.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));if(out.some(x=>x.errors.length||!x.withinViewport||x.overflows||!x.channels||!x.emoji||!x.emojiLimit||!x.keyboardTab||!x.collapse||!x.offline||(!x.touchDragLocked&&(!x.rightDrag||!x.leftDrag))||x.buttons!==(x.admin?1:0)||x.commands!==(x.admin?25:0)))process.exitCode=1;})();




